### ISSUE TITLE
Documentation is fairly incomplete, the tool seems quite hard to use

### ISSUE THREAD

**Issue by ejgallego** [ocamllabs/dune-release#127]
As seen in https://github.com/garrigue/lablgtk/pull/38#issuecomment-462097726 , migrating packages to use `dune-release` is a very frustrating experience.

Contrary to what is claimed, many critical invariants [such as that `homepage` must be set to github, format of CHANGES, etc...] don't seem to be properly documented, and in the cases that the right hidden magic is not properly set the tool behaves in random ways [such as setting URLs incorreclty, publishing arbitrary changelogs, etc...]

IMHO what works and what does not should be much better documented, likely with a guiding example.

cc: @garrigue

**Comment by dinosaure** [comment]
I agree, specially about `CHANGES.md` where I had struggle about format of version.

**Comment by samoht** [comment]
Do you see concrete items that could be improved ? A random list, from what I understand:

- [ ] improve version detection from CHANGES.md (and/or improve documentation)
- [ ] better linting of which fields much be set
- [ ] write a guiding examples.

Do you see something else?

**Comment by ejgallego** [comment]
Thanks @samoht , I think maybe the biggest remaining point for me is to detail what requires github and what not, in particular more info indeed about the fields.

**Comment by samoht** [comment]
> improve version detection from CHANGES.md (and/or improve documentation)

The tools is now displaying more information during version detection (#135)

**Comment by NathanReb** [comment]
We'll try to also improve the documentation so new users have a good introduction before actually launching the tool!
