### ISSUE TITLE
`dune-release` should remove the `version` field in opam files

### ISSUE THREAD

**Issue by samoht** [ocamllabs/dune-release#189]
I'm using 79432f3cd652780eee510e09b21e978273cfc056 and the irmin release lead to: https://github.com/ocaml/opam-repository/pull/15363

That would be nice to remove the existing version fields on opam files before doing a release.

**Comment by NathanReb** [comment]
That might be a recently introduced bug. I had to fix some issues with the parts that does remove existing version fields to fix #163. I'll take a look!

**Comment by kit-ty-kate** [comment]
The version field in https://github.com/ocaml/opam-repository/pull/15805 was also wrong. Can this be fixed?
