### ISSUE TITLE
Checksums of `.tbz` is incorrect in generated opam files

### ISSUE THREAD

**Issue by tmattio** [ocamllabs/dune-release#209]
I'm trying to release a package on Opam with `dune-release`.

I've run `dune-release` several times, and it exits succesfully, but the checksums of the generated opam file does not match the checksum of the `.tbz` file uploaded as a Github Release artificat.

For instance, one run of `dune-release`  created this archive:
https://github.com/tmattio/inquire/releases/download/v0.1.0/inquire-v0.1.0.tbz

And the follwing opam file:
https://github.com/ocaml/opam-repository/commit/11a349a888927aa7663300998310e3cc6fe21787

But when running:
```
shasum -a 256 inquire-v0.1.0.tbz
shasum -a 512 inquire-v0.1.0.tbz
```
I have different results.

Am I missing something?

On a side note, thanks a lot for creating dune-release, it makes the release process really easy!

Thanks!

**Comment by gpetiot** [comment]
Sorry for taking so long to investigate this. I've made some tests and for me the checksum of the opam file is the same as the one shasum computes from the archive.

If you repo is dirty you may see a warning being printed in the terminal saying "The opam package may be inconsistent with the distribution" but if everything is alright the checksums should be consistent.

**Comment by gpetiot** [comment]
I'm closing it, feel free to re-open if the issue arises again in the future.
