### ISSUE TITLE
Make runtime dependency handling more consistent and document it

### ISSUE THREAD

**Issue by sternenseemann** [ocamllabs/dune-release#238]
I am currently in the midst of packaging `dune-release` for NixOS. Therefore I was looking through the code for runtime
dependencies, i. e. executables that get called. As far as I understand there are two types of runtime dependencies:

1. Some are just expected to be in `PATH`, like coreutils (fair enough) or `ocamlfind`
2. Some have an environment variable configuring the path to their binary, if that is not present, `dune-release` looks for it in `PATH` (git, bzip2, …)

I noticed however that the implementation of the second type of runtime dependencies is in some cases inconsistent: For example, git is configured by `DUNE_RELEASE_GIT` in `lib/vcs.ml`, but assumed to be in `PATH` by `lib/github.ml`.

It would be great if this area of `dune-release` could be made more consistent and documented better. A list of runtime dependencies (or executables called at runtime) and the environment variables that configure them would be great!

**Comment by gpetiot** [comment]
Indeed, @NathanReb @pitag-ha how about we don't try to read these env variables and just assume everything is in `PATH` ?

We have:
- `DUNE_RELEASE_BZIP2`
- `DUNE_RELEASE_TAR`
- `DUNE_RELEASE_GIT`
- `DUNE_RELEASE_HG`

**Comment by NathanReb** [comment]
Yeah we should totally list all those runtime deps, maybe even add them as depext in opam if it's not the case already. Let's start with that!

I also agree we should drop the env vars but that would have to wait for the 2.0 release. We should deprecate them and document PATH as the preferred way to find those external binaries!

**Comment by sternenseemann** [comment]
Additionally there is also `HOST_OCAMLC`, `BUILD_OCAMLC`, `HOST_OCAMLCP`, … in `lib/opam.ml`. After reading the code I am not 100% sure how this behaves in practice probably good to document as well, I guess it's related to cross-compiling.

I think dependency-specific env vars are kinda neat, but I'd rather drop them instead of having inconsistent behavior.

**Comment by gpetiot** [comment]
Good catch, I added these variables to the README (they are only used for the opam binary though, so I only listed these ones, the code could to be simplified soon).

**Comment by sternenseemann** [comment]
Thanks for your help on this btw, got `dune-release` packaged for NixOS now: <https://github.com/NixOS/nixpkgs/commit/c4ca9ba10d66ca5479d816f60c251b5593536d97>

**Comment by gpetiot** [comment]
Great, thanks!
