### ISSUE TITLE
Sort package names alphabetically in Opam PR

### ISSUE THREAD

**Issue by CraigFe** [ocamllabs/dune-release#249]
When releasing multiple packages at once, `dune-release` seems to pick an arbitrary order for the package names in the release. For instance:

```
[new release] alcotest-lwt, alcotest, alcotest-async and alcotest-mirage (1.2.0)
Open • CraigFe wants to merge 1 commit into master from release-alcotest-1.2.0


  Lwt-based helpers for Alcotest

  • Project page: https://github.com/mirage/alcotest
  • Documentation: https://mirage.github.io/alcotest

  ##### CHANGES:
```

When it does this, it constructs the PR description from the first package in the list. It'd be good to have some way of giving `dune-release` either a file from which to take the description (à la [`hub`](https://hub.github.com/) `pull-request -F <FILE>`), or to tell it that one particular package is the "canonical" one and should always appear first. (The latter would suffice for all of the projects I regularly release.)

**Comment by CraigFe** [comment]
After some further thought, it also seems fine for `dune-release` to just not try to find a package description when there are multiple in the repository.

**Comment by NathanReb** [comment]
I wonder if we haven't fixed that already on master. I remember another issue on this topic, I'll take a look.

Sorting seems fine indeed, I wonder if there isn't already some logic to use the shortest name as the "main package" name.

I also agree it should be fine not to include the description when releasing several packages at once.
