### ISSUE TITLE
GitHub Token from the environment?

### ISSUE THREAD

**Issue by phated** [ocamllabs/dune-release#273]
I'm exploring automatic opam releases using GitHub Actions, which can provide a GitHub token through an environment variable. However, it seems that `dune-release` only supports having a token written to the filesystem.

Could this accept a token from the environment before checking for it on the filesystem?

**Comment by NathanReb** [comment]
Yeah this makes sense if we ever want to release from any kind of CI!

Would you like to give it a try? I'm happy to point you in the right direction if needed!
