### ISSUE TITLE
Feature request: add changelog to annotated tag message

### ISSUE THREAD

**Issue by emillon** [ocamllabs/dune-release#274]
Hi,

Annotated tags (the kind `dune-release` uses) have messages attached to them (like commits).

At the moment the string `"Distribution x.y.z"` is used (can be overridden on the commandline).
I'm thinking it could contain the changelog section corresponding to this release (the one that's used in the github release and opam PR).

How does that sound?

**Comment by NathanReb** [comment]
I like the idea that one could run `git show <tag>` and see the changelog without having to browse github, can be helpful when working with a local copy!

**Comment by emillon** [comment]
(this piece of information is displayed by `git show $tagname`)
