### ISSUE TITLE
Support Submodules

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/dune-release#279]
Submodules are currently ignored when dune-release creates an archive. It would be much better if it was possible to include them as part of the source.

Perhaps there should be an option to switch off this behavior. I know some use submodules for brining into scope normal dependencies during development.

**Comment by kit-ty-kate** [comment]
I'm having the same issue while trying to release https://github.com/kit-ty-kate/waylaunch

**Comment by NathanReb** [comment]
Great timing! I just opened a PR with submodules support here: #300. Do you want to give it a try and see if the generated tarball fits your requirements?
