### ISSUE TITLE
unclear error message about (name <name>) with several .opam files

### ISSUE THREAD

**Issue by lehy** [ocamllabs/dune-release#321]
## Setup

We set up a simple repo with two .opam files. We add a name to
dune-project and commit it. The name is different from both .opam
files.

~~~
> git clone git@github.com:lehy/dune-release-repro.git
[snip]
> cd dune-release-repro
liba/  libb/  CHANGES  dune-project  dune-workspace  liba.opam  libb.opam
> cat dune-project 
(lang dune 2.7)
~~~

~~~
> echo '(name toto)' >> dune-project
> git add dune-project && git commit -m 'add name'
> cat dune-project
(lang dune 2.7)

(name toto)
~~~

`dune-release tag` works:

~~~
> dune-release tag        
[-] Extracting tag from first entry in CHANGES
[-] Using tag "1.0.0"
[?] Create git tag 1.0.0 for HEAD? [Y/n]
y
[+] Tagged HEAD with version 1.0.0
~~~

## Problem

`dune-release distrib` complains that it does not like our name, even
if this name is arbitrary, with a confusing error message. It wants
this name to match one of our .opam files.

~~~
> dune-release distrib
[-] Building source archive
File "dune-project", line 3, characters 6-10:
3 | (name toto)
          ^^^^
Error: Package toto doesn't exist. Please add a (package (name toto) ...)
stanza to your dune-project file.
dune-release: [ERROR] run ['dune' 'subst']: exited with 1
~~~

It would be nice either to remove this limitation (accept any name) or
to clarify the error message.

**Comment by lehy** [comment]
I now understand that this is a limitation in dune itself. Not sure there is value in keeping this bug open.

**Comment by NathanReb** [comment]
Indeed this is a dune error. I'm closing this!
