### ISSUE TITLE
dune-release distrib --name does not suffice to set name

### ISSUE THREAD

**Issue by lehy** [ocamllabs/dune-release#324]
`dune-release distrib` calls `dune subst`, which requires a `(name <name>)` stanza in dune-project. Therefore, trying to set the name with `dune-release distrib --name <name>` is bound to fail with errors like:

~~~
+    Error: The project name is not defined, please add a (name <name>) field to
+    your dune-project file.
+    dune-release: [ERROR] run ['dune' 'subst']: exited with 1
+    [3]
~~~

One solution might be to remove `--name` from `dune distrib`, and mandate a `(name <name>)` stanza in dune-project. Another one would be to patch `dune subst` to accept an argument to set the project name.

**Comment by NathanReb** [comment]
I think enforcing a name in the dune-project is reasonable enough!
