### ISSUE TITLE
Opam release branch doesn't track the remote PR branch

### ISSUE THREAD

**Issue by CraigFe** [ocamllabs/dune-release#336]
A very minor papercut when using `dune-release` to create an `opam-repository` PR is that the release branch (of the form `release-<pkg>-version`) that is created doesn't have its tracking information set properly, so making any modifications to the release requires first setting this with `--set-upstream-to origin` or similar.

I suspect that `dune-release` has enough information to do this automatically while creating the branch.

**Comment by gpetiot** [comment]
Hi, I only briefly looked into it (as I didn't have to use anything similar before), do you mean adding `--set-upstream` when pushing the release branch?

**Comment by CraigFe** [comment]
Exactly; I think either `--set-upstream` on push or `--track` [on checkout](https://github.com/ocamllabs/dune-release/blob/master/lib/vcs.ml#L145) would fix this. I had a quick look into implementing it, but didn't want to accidentally introduce an inconsistency between Mercurial and Git due to never having used the former; happy to come back to it later if I get time :slightly_smiling_face:
