### ISSUE TITLE
Check for {dune, dev-repo} in .opam and name field dune-project in dune-release lint check

### ISSUE THREAD

**Issue by shakthimaan** [ocamllabs/dune-release#347]
Add the following checks in `dune-release`:

1. The presence of `dune` in `depends` in the .opam file.
Reference: https://github.com/ocaml/opam-repository/pull/18176/commits/d89df75f1ef71fdbe1de5b13d6a420f74be544bb

2. The `dev-repo` field needs to be specified. Linting says things are fine, but, publishing complains of missing dev-repo.
```
$ dune-release lint 
[ OK ] File README is present.
[ OK ] File LICENSE is present.
[ OK ] File CHANGES is present.
[ OK ] File opam is present.
[ OK ] lint opam file rungen.opam.
[ OK ] opam field description is present
[ OK ] opam fields homepage and dev-repo can be parsed by dune-release
[ OK ] Skipping doc field linting, no doc field found
[ OK ] lint /home/guest/rungen success

$ dune-release publish 
[-] Skipping documentation publication for package rungen: no doc field in rungen.opam
[-] Publishing distribution
[-] Publishing to github
dune-release: [ERROR] The field dev-repo is missing in rungen.opam.
```
3. Add name field in `dune-project`.
```
$ dune-release distrib
[-] Building source archive
Error: The project name is not defined, please add a (name <name>) field to
your dune-project file.
dune-release: [ERROR] run ['dune' 'subst']: exited with 1
```

The above are observed in dune-release.1.4.0.

**Comment by NathanReb** [comment]
Thanks for reporting this issue, it would indeed be nice to add those checks. We're working on a separate, more dune-releasability focused command here: #318. These would probably fit in there, cc @pitag-ha.

We might do it as part of the 2.0 release though as we will have cleaned up the default behaviour a bit and it will be easier to define clear rules regarding what fields should be set for dune-release to work. Before 2.0, the delegates kind of prevent us from doing that!

**Comment by pitag-ha** [comment]
> 2. The dev-repo field needs to be specified. Linting says things are fine, but, publishing complains of missing dev-repo.

That's checked for in the new `check` command. See [here](https://github.com/ocamllabs/dune-release/pull/318/files#diff-2f79af1e5fca625edf8ae20c997affc5a558a999c60b5d3c903026ef31d4b972R131). The new `check` command will be available from the next release on. 

> 3. Add name field in dune-project.

That's a great idea, thanks! I've also added that to the new `check` command now. See [here](https://github.com/ocamllabs/dune-release/pull/351/commits/35aa5b8e17d97a5e26e6c06a712042b9c046b459#diff-2f79af1e5fca625edf8ae20c997affc5a558a999c60b5d3c903026ef31d4b972R33).

> 1. The presence of dune in depends in the .opam file.

To me, that seems more like a job for the CI than for a release tool. What do you think? In fact, opam CI includes that check by running `opam-dune-lint`.

**Comment by shakthimaan** [comment]
Thanks for adding the checks.
> that seems more like a job for the CI than for a release tool ... opam CI includes that check by running opam-dune-lint.
If there is something that we can catch at the developer end (using static checks, linting etc.) before it hits the CI, it is better to add it up front.

**Comment by pitag-ha** [comment]
> If there is something that we can catch at the developer end (using static checks, linting etc.) before it hits the CI, it is better to add it up front.

What I wrote was a typo, sorry. I wanted to write ocaml-CI, not opam CI. So what I mean is that the CI of the project (not the CI of the opam-repository) could catch that front up. Does that sound better?

**Comment by pitag-ha** [comment]
I'm closing this, since two of the mentioned checks are implemented in master now and with respect to the third one we've agreed that it can be done by the CI of the project rather than by dune-release. Thanks for your input, @shakthimaan!
