### ISSUE TITLE
`dune-release tag` is confused by branch / tag name collisions

### ISSUE THREAD

**Issue by CraigFe** [ocamllabs/dune-release#365]
`dune-release tag` currently uses e.g. `git rev-parse --verify 1.2.3`  to check that the `1.2.3` tag doesn't already exist before creating it. This will produce a false-positive if the user has a _branch_ named `1.2.3` instead:

```sh
; git checkout -b 1.2.3
; dune-release tag
[-] Extracting tag from first entry in CHANGES.md
[-] Using tag "1.2.3"
[-] Nothing to be done: tag already exists.
```

It's probably not a good idea to name a branch "`1.2.3`", but it seems worth defending against anyway.

I think `dune-release tag` can use `git tag --verify` as a better test for tag existence, and refer to the tag ref explicitly to avoid ambiguity in subsequent usages (i.e. `refs/tags/1.2.3` rather than just `1.2.3`).

**Comment by Leonidas-from-XIV** [comment]
Just saw this issue and I seem to have independently (great minds... find the same bugs, or so) and fixed it in #389, so I'm gonna close this as fixed.
