### ISSUE TITLE
Wrong distrib name with dune-release 1.5.0

### ISSUE THREAD

**Issue by voodoos** [ocamllabs/dune-release#381]
When releasing Merlin `dune-released` refused to sue the tag name as a version for the archive file and the release name. Instead it used the name `merlin` leading to the confusing archive name `merlin-merlin.tbz`.

```
$ dune-release tag v4.3-411
$ dune-release distrib
[-] Building source archive
[+] Wrote archive _build/merlin-merlin.tbz
```

With `dune-release` 1.4.0 I get the expected behavior:
```
$ dune-release tag v4.3-411
$ dune-release distrib
[-] Building source archive
[+] Wrote archive _build/merlin-v4.3-411.tbz
```

I wonder if that could come from undesirable tag detection since our changelog starts with:
```
merlin 4.3
----------
changes....
```

To reproduce, you can do a dry run on current merlin master.

**Comment by NathanReb** [comment]
This is from https://github.com/ocamllabs/dune-release/pull/271, we kind of saw it coming at the time, not sure why we decided not to do the proposed reverse tag parsing thing.

I'll work on a fix!

Out of curiosity is there any reason why you don't want to follow dune-release expected changelog scheme?

**Comment by voodoos** [comment]
> Out of curiosity is there any reason why you don't want to follow dune-release expected changelog scheme?

Just plain old conservatism... and to provide nice edge-cases for `dune-release` testing! *cough*

**Comment by gpetiot** [comment]
Maybe we should add a more verbose output (à la autoconf/configure) to `dune-release check` so we can output the tag, the version, etc. to avoid bad surprises like these.

**Comment by Leonidas-from-XIV** [comment]
@voodoos Could you please try out the branch in #383? We changed the logic of #271 to simplify the escaping rules and to read the version back from the tag when using `distrib` so it should.. just work again.

**Comment by voodoos** [comment]
> @voodoos Could you please try out the branch in #383? We changed the logic of #271 to simplify the escaping rules and to read the version back from the tag when using `distrib` so it should.. just work again.

I have nothing to release right now... but we should have a Merlin release in one or two weeks...
