### ISSUE TITLE
Remove support for opam 1.2 CLI

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocamllabs/dune-release#406]
At the moment we still support the opam 1.2.2 client. There are [very few distributions](https://repology.org/project/opam/versions) that do not have an opam 2.x available these days (mostly Gentoo forks like Exherbo and Funtoo), so this support these days is mostly untested (we don't test it in CI because we don't have an opam 1.2 system available), OPAM Repository doesn't continue to maintain 1.2 format packages.

For this reason it would be reasonable to remove support for the old version to simplify our code.

Users that are stuck on very old Debian or Ubuntu versions can continue to use the pre-2.x versions of `dune-release` which continue to be available, or using a third-party repository to get a newer OPAM. Given releases are usually done from developer machines the impact of not supporting 2017-era distributions should be minimal.

**Comment by NathanReb** [comment]
As a side note, I think we should still detect client version but simply error out when it's 1.2 or lower instead of maintaining that complex alternate code path.

**Comment by Leonidas-from-XIV** [comment]
@NathanReb Personally I am not sure, since it seems to me that encountering an opam 1.2 on a developer machine (where `dune-release` would run) seems to me rather unlikely, one would need to not have updated their system for several years (Ubuntu 18.04, Debian 9, maybe some CentOS but I've yet to see someone developing on CentOS in the first place).

So maybe we can just remove the code altogether? OPAM 2.0.0 was released over 5 years ago by now. Distributions packaging a future `dune-release` 2.0.0 release wouldn't even have OPAM 1.2 in their repos anymore.
