### ISSUE TITLE
Create `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocamllabs/dune-release#423]
In #421 a good point was raised that we don't have a stated policy on contributions. I am sure we can take some inspiration from MDX' [`CONTRIBUTING.md`](https://github.com/realworldocaml/mdx/blob/main/CONTRIBUTING.md) and add it to this project so people know that outside contributions are definitely welcome!

**Comment by NathanReb** [comment]
Good point, that would be great indeed!
