### ISSUE TITLE
distribution archive may be inconsistent

### ISSUE THREAD

**Issue by hannesm** [ocamllabs/dune-release#443]
First of all thanks for the tool to make releases to the opam repository easier. I don't quite understand this message:

```
$ dune-release bistro
[-] Building source archive
dune-release: [WARNING] The repo is dirty. The distribution archive may be
                        inconsistent. Uncommitted changes to files (including
                        dune-project) will be ignored.
```

A `git status` indeed reports various untracked files. But my intuition was that dune-release would use the latest git commit / git tag for construction the tarball? Would be great to clear up what is used for the tarball creation, and that the above message is only emitted if the source tarball is indeed not reproducible from the git tag.

**Comment by NathanReb** [comment]
Indeed, the tarball is built from the git commit/tag. I think the warning's original intent was to warn users that they had local change that would not make it into the release tarball.

I agree the phrasing is not entirely clear and can be confusing. I'll update the warning message to better reflect that!
